### PR TITLE
Ghc 8.4

### PR DESCRIPTION
**Pull request by dfithian**

### CODE REVIEW

**Comment by k-bx** [comment]
Would adding also a nightly work? (to actually check in GHC 8.4)

Sorry, nevermind, it's already there

**Comment by dfithian** [comment]
@k-bx Yeah the reason I got this was because a dependency failed to build with the nightly resolver (for GHC 8.4) in stackage:
https://github.com/fpco/stackage/issues/3394#issuecomment-373878289

**Comment by k-bx** [comment]
@dfithian please do something like here https://github.com/informatikr/hedis/pull/104/files with a conditional dependency for older GHC

**Comment by dfithian** [comment]
I don't see any reason to support older GHC. When I updated this package to version 2.0.0 it was unusable with previous LTS/GHC. I think if the current builds complete successfully there's no reason to explicitly include or exclude the semigroups package and doing so would only make the build more complicated.

**Comment by k-bx** [comment]
@dfithian yeah, makes sense

@iand675 can you please upload the 0.2.2.0 or give me the rights to do so on Hackage? Thanks!

**Comment by dfithian** [comment]
I can upload this later today

**Comment by dfithian** [comment]
https://hackage.haskell.org/package/datadog

**Pull request merged**
