### PR TITLE
Do not build classy lens things with haddock - move types and lens to…

### PR DESCRIPTION
**Pull request by dfithian**
When I run `stack build --haddock` now it does not exit. You do have to click through to `Network.Datadog.Internal.Types` to see the actual docs, though.

### CODE REVIEW

**Comment by goakley** [comment]
Well spotted, thank you!  Will leave to @iand675 for final say on merge, but looks good.

**Comment by iand675** [comment]
I'm not super crazy about having to dig into "internal" modules to see the actual docs. Is there any downside to having the Types and module not be internal (e.g. `Network.Datadog.Types`) and reexporting lens stuff from `Network.Datadog.Lens`? It wouldn't technically break compatibility on Hackage since there's not a 0.2 release there yet.

**Comment by dfithian** [comment]
Sure, I can do that. I was being lazy because a lot of modules import lenses from Network.Datadog.Types :P

**Comment by dfithian** [comment]
Alright, should be good now

**Review by iand675 — APPROVED** [review]

**Pull request merged**
